version: '2'
networks:
  miner:
    driver: bridge
services:
  miner:
    image: miner
    build: ./miner
    depends_on:
      - rabbitmq
    ports:
      - "6000:6000"
    networks:
      - miner
  mitie:
    image: mitie
    build: ./mitie
    depends_on:
      - rabbitmq
    networks:
      - miner
  relevancy:
    image: relevancy
    build: ./relevancy
    depends_on:
      - rabbitmq
    networks:
      - miner
  quad:
    image: quad
    build: ./quad
    depends_on:
      - rabbitmq
    networks:
      - miner
  collector:
    image: collector
    build: ./collector
    depends_on:
      - rabbitmq
    networks:
      - miner
    volumes:
      - ./data:/src/data
  rabbitmq:
    image: rabbitmq:alpine
    expose:
      - "5672"
    networks:
      - miner
